language: ruby
env:
- DB=postgresql
addons:
  postgresql: 9.6
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database konnekt_test;' -U postgres
dist: trusty
rvm:
- 2.4.1
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
- bundle exec rspec